help = "Run tester commands"

########################################################

[command.test_bash]
help = "Test bash executor"
platform = ["Client"]

[command.test_bash.executor]
tail = "tests/run"
executor = "bash"

[command.test_bash.args.key]
help = "Set dummy 'key' for command"
arg_index = 1
value_is = "String" # Boolean | String | Array
required = true

[command.test_bash.args.val]
help = "Set dummy 'value' for command"
arg_index = 2
value_is = "String" # Boolean | String | Array
required = true

[command.test_bash.args.flag]
help = "Set dummy boolean flag for command"
long = "flag"
short = "f"
value_is = "Boolean" # Boolean | String | Array
to_env_key = "TESTER_BASH_FLAG"
required = false

########################################################

[command.test_lua]
help = "Test lua executor"
platform = ["Client"]

[command.test_lua.executor]
tail = "tests/run"
executor = "lua"

[command.test_lua.args.key]
help = "Set dummy 'key' for command"
arg_index = 1
value_is = "String" # Boolean | String | Array
required = true

[command.test_lua.args.val]
help = "Set dummy 'value' for command"
arg_index = 2
value_is = "String" # Boolean | String | Array
required = true

########################################################

[command.test_perl]
help = "Test perl executor"
platform = ["Client"]

[command.test_perl.executor]
tail = "tests/run"
executor = "perl"

[command.test_perl.args.key]
help = "Set dummy 'key' for command"
arg_index = 1
value_is = "String" # Boolean | String | Array
required = true

[command.test_perl.args.val]
help = "Set dummy 'value' for command"
arg_index = 2
value_is = "String" # Boolean | String | Array
required = true

[command.test_perl.args.flag]
help = "Set dummy boolean flag for command"
long = "flag"
short = "f"
value_is = "Boolean" # Boolean | String | Array
to_env_key = "TESTER_PERL_FLAG"
required = false

########################################################

[command.test_python]
help = "Test python executor"
platform = ["Client"]

[command.test_python.executor]
tail = "tests/run"
executor = "python"

[command.test_python.args.key]
help = "Set dummy 'key' for command"
arg_index = 1
value_is = "String" # Boolean | String | Array
required = true

[command.test_python.args.val]
help = "Set dummy 'value' for command"
arg_index = 2
value_is = "String" # Boolean | String | Array
required = true

[command.test_python.args.flag]
help = "Set dummy boolean flag for command"
long = "flag"
short = "f"
value_is = "Boolean" # Boolean | String | Array
to_env_key = "TESTER_PYTHON_FLAG"
required = false

########################################################

[command.test_sh]
help = "Test sh executor"
platform = ["Client"]

[command.test_sh.executor]
tail = "tests/run"
executor = "sh"

[command.test_sh.args.key]
help = "Set dummy 'key' for command"
arg_index = 1
value_is = "String" # Boolean | String | Array
required = true

[command.test_sh.args.val]
help = "Set dummy 'value' for command"
arg_index = 2
value_is = "String" # Boolean | String | Array
required = true

[command.test_sh.args.flag]
help = "Set dummy boolean flag for command"
long = "flag"
short = "f"
value_is = "Boolean" # Boolean | String | Array
to_env_key = "TESTER_SH_FLAG"
required = false

########################################################
