[dependency.bash]
optional = false
scope = "Node" # Node | Cluster | Project | Client
collection = "Executor"

[dependency.lua]
optional = false
scope = "Node" # Node | Cluster | Project | Client
collection = "Executor"

[dependency.perl]
optional = false
scope = "Node" # Node | Cluster | Project | Client
collection = "Executor"

[dependency.python]
optional = false
scope = "Node" # Node | Cluster | Project | Client
collection = "Executor"

[dependency.sh]
optional = false
scope = "Node" # Node | Cluster | Project | Client
collection = "Executor"
